---
language: cpp
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libboost-test-dev
    - build-essential
    - libssl-dev
    - libdb-dev
    - libdb++-dev
    - libqrencode-dev
    - qt5-default
    - qt5-qmake
    - qttools5-dev-tools
    - libminiupnpc-dev
    - libzip-dev
    - autoconf
    - automake

script:
  - ./autogen.sh
  - mkdir build
  - cd build
  - ../configure --with-gui=qt5 --with-incompatible-bdb
  - make
